### ISSUE TITLE
18A9 is partly below line

### ISSUE THREAD

**Issue by Mercury13** [notofonts/mongolian#34] opened 2023-10-31 21:02 UTC
### Title
18A9 is partly below line. Or maybe on the left of column.

### Font
NotoSansMongolian-Regular.ttf

### Where the font came from, and when
Site: this repo, beta branch
Date: 2023-10-31

### Font Version
3.000

### OS name and version
W10 22H2

### Application name and version
Qt 6.1.3, but just sometimes (QLabel OK, painting on canvas troubles)

### Issue
18A9’s bottom is −388
OS/2 typo descent is −264
As it’s the only anchored umlaut, maybe it’s better to anchor it to every letter individually? I’m not in favour of increasing descent.

### Character data
U+18A9 Mongolian letter Ali gali Dagalga

### Screenshot
![image](https://github.com/notofonts/mongolian/assets/10164882/2bd43427-ff93-4550-b8c9-35e7f9447f60)
![image](https://github.com/notofonts/mongolian/assets/10164882/bf482f8c-5096-4a66-b0c4-99075c095edd)

**Comment by lianghai** [comment] 2023-11-01 21:33
The font supports three anchored marks for Mongolian characters:

- U+1885 ᢅ MONGOLIAN LETTER ALI GALI BALUDA
- U+1886 ᢆ MONGOLIAN LETTER ALI GALI THREE BALUDA
- U+18A9 ᢩ MONGOLIAN LETTER ALI GALI DAGALGA

Vertical metrics should be adjusted to whatever needed.

> … maybe it’s better to anchor it to every letter individually?

Can you clarify what you were suggesting?

**Comment by Mercury13** [comment] 2023-11-01 21:44
> Can you clarify what you were suggesting?
As I said, I’m against increasing vertical metrics.
As anchor 0 serves 18A9 dagalga only (baludas are on the top), it’d be better to anchor every letter individually instead of mass-anchoring to (0, 0).

**Comment by Mercury13** [comment] 2023-11-01 21:49
@lianghai I mean: leave default position as is, but anchor dagalga upper/lower depending on where the letter has room for dagalga.

**Comment by lianghai** [comment] 2023-11-01 22:02
That doesn’t sound helpful for reducing the winDescent value.

**Comment by Mercury13** [comment] 2023-11-01 22:47
Of course you can, and that’s the simplest solution (388 if you want). But dagalga isn’t so important umlaut.

**Comment by Mercury13** [comment] 2023-11-02 11:36
@lianghai So, which letters may actually carry dagalga? I see problems in…
uni182C.Gx and other letters with dots
uni1827.W.medi (and final too)
uni1821.Aa.fina
uni182B.P.fina
uni1839.F.init._isol and other forms
uni183A.K2.fina
uni183B.K.fina
uni183C.C.fina (near miss but anchorable)
uni183E.Hr.medi and likes
uni1868.Db.medi and uni1868.D.medi
Ligatures starting with Pg
If these are actually important → then increase, of course…

**Comment by lianghai** [comment] 2023-11-02 12:12
> That doesn’t sound helpful for reducing the winDescent value.

Okay, first, I just realized that I was completely confused by your original analysis:

> 18A9’s bottom is −388
> OS/2 typo descent is −264
> … I’m not in favour of increasing descent.

I somehow thought you were referring to the clipping area set by WinAscent/WinDescent. Now I see you were comparing this mark with TypoDescender. Then the answer to this comparison is—it doesn’t matter.

The TypoAscender/TypoDescender pair sets the default line height, as in the default distance between two baselines. It’s not meant to be a region that encloses all outlines. TypoAscender/TypoDescender only needs to be increased when something is causing frequent, unacceptable clashing in common texts.

Therefore this is a non-issue you’re commenting on.

**Comment by Kushim-Jiang** [comment] 2023-11-02 12:19
In this version, we simply anchored the marks (baluda, triple baluda and dagalga) in a fixed position to the base glyph (including variants, ligatures and the dotted circle), so in order to avoid collision with all the glyphs used in Hudum Ali Gali, the marks are positioned relatively far from the nirugu. We feel that a better design would be to design matching anchor position for the glyph one by one.

**Comment by Mercury13** [comment] 2023-11-02 12:20
@lianghai I say the same, it’s better to leave those values as are. So may I anchor that dagalga individually to every character it’s anchored to? Let it be below line by default, but if outline permits, it’ll be moved closer?

**Comment by lianghai** [comment] 2023-11-02 12:26
A “better design” only makes sense when you have actual text you want to improve the rendering for. It’s a waste of time to anchor a mark “individually” when you don’t even know which exact combinations matter.

**Comment by Mercury13** [comment] 2023-11-02 12:38
That’s why I’m asking you. My solution is…
1. Move anchor on dagalga lower, probably to half or 2/3 of stroke.
2. Automatically move anchor on base characters lower, but not so much, so dagalga will be inside line.
3. Automatically check all glyphs, and if the anchor is lower than every glyph’s point → do nothing, otherwise mark them somehow.
4. Manually check marked glyphs whether they can accommodate dagalga. If cannot → move even lower, no matter that it’s outside line.

**Comment by Mercury13** [comment] 2023-11-02 12:52
I actually need just 25CC+dagalga. But I checked Mongolian Baiti, and it does almost what I said, except their dagalga’s anchor is in a strange place, and their line is rather tall.

**Comment by Mercury13** [comment] 2023-11-02 13:10
I actually need just 25CC+dagalga. But it affects ALL texts with dagalga. And I checked Mongolian Baiti, and it does almost what I said, except their dagalga’s anchor is in a strange place, and their line is rather tall.
As dagalga cannot live without anchor, I trust you: if you put the anchor, then it’s important.

**Comment by Mercury13** [comment] 2023-11-02 13:12
Usually such umlauts are put in a safe-bet place by default, and dagalga isn’t an exception. But as it cannot live w/o anchor → that’s why I’m asking.

**Comment by Mercury13** [comment] 2023-11-02 13:44
For rare umlauts — they don’t have to be inside line, but if they are, it’s cool.

**Comment by simoncozens** [comment] 2023-11-04 07:52
FWIW, to avoid regressions I'm going to be setting the vertical metrics to the same as the previous versions on Google Fonts.

**Comment by Mercury13** [comment] 2023-11-04 10:50
If it used to → go on!

**Comment by Mercury13** [comment] 2023-11-04 11:53
![image](https://github.com/notofonts/mongolian/assets/10164882/41a0c766-05a2-4f89-8947-b62b22efb0a5)
![image](https://github.com/notofonts/mongolian/assets/10164882/1f66a15e-8dd8-4ce5-8508-9d3355fab1a9)
![image](https://github.com/notofonts/mongolian/assets/10164882/aadf3524-99c3-4c79-aee1-e43f7420f484)
Is that what you wanted?
As this umlaut is VERY rare, I’ll better try to place it automatically by making some sort of hitbox.

**Comment by Mercury13** [comment] 2023-11-04 11:56
The hitbox should be two-tiered: red = never cross, yellow = raise an alarm and make me to resolve it manually.
![image](https://github.com/notofonts/mongolian/assets/10164882/e897cf29-bfeb-4ad4-98f5-8ee46dc4ca19)

**Comment by Mercury13** [comment] 2023-11-04 11:57
The hitbox should be two-tiered: red = never cross, yellow = raise an alarm.
![image](https://github.com/notofonts/mongolian/assets/10164882/b79d51c5-6bd0-4533-a439-4d23e951662b)

**Comment by Mercury13** [comment] 2023-11-04 12:14
I know what to do, just give time. I also tested your examples, they don’t have dagalga.

**Comment by lianghai** [comment] 2023-11-04 14:28
> For rare umlauts — they don’t have to be inside line, …

Then nothing needs to change here.

> … but if they are, it’s cool.

No. Making widespread changes without understanding the use cases is not cool.

> This is well-established practice for most umlauts: anchor on base shows its actual top/bottom, anchor on mark makes space.

Dagalga is not a usual combining mark, therefore no need to explain how combining marks are usually anchored. The three Mongolian combining marks in this fonts are intentionally anchored like this to ensure they’re legible with minimal maintenance cost. The anchoring should stay in this way until use cases in actual texts suggest a better anchoring strategy.

If you’re suggesting the font should be fixed because your software can’t render such a mark, fix your software.

**Comment by Mercury13** [comment] 2023-11-04 15:00
Then I’ll add another anchor at (0, 0), and the only two who are anchored manually are…
1. 25CC.
2. All variations of Galik AH, I’ve actually seen it with dagalga.

It’d be cool to have several anchors on dagalga and choose them in some order (first “daga”, then “mong”), but IDK whether it works.

**Comment by Mercury13** [comment] 2023-11-04 15:09
IDK how you maintain characters, and if I mass-put that anchor in the same point but lower (e.g. in 0, −100) → is it OK? Again, only 25CC and Galik AH will be anchored manually.

**Comment by Mercury13** [comment] 2023-11-04 15:20
So I see four solutions.
1. Add another anchor. Auto-put it at (0, min{0, lowest_y}). This was my idea.
2. Add another anchor. Auto-put it at e.g. (0, −250), I’ll choose some multiple of 10 for simplicity.
3. Add another anchor. Auto-put it at (0, 0). Maybe it’ll be easier for you (IDK), but hand-anchoring will be royal pain!
4. Add another anchor. Put it manually on 25CC and Galik AH only. Write GPOS in such a fashion that it should use first “daga”, then “mong”. IDK how to implement and whether it works, but it’s the best solution ever.

**Comment by simoncozens** [comment] 2023-11-04 16:55
> The anchoring should stay in this way until use cases in actual texts suggest a better anchoring strategy.

Liang is an expert in this area and I'm inclined to agree with him.

I don't actually see that there's a problem here to be fixed. I understand for your use case that you are *very* concerned about what dotted circles look like. But in ordinary text use, a dotted circle is an *error message*. I don't actually care whether the error message suffers from clipping or not.

**Closed by simoncozens** 2023-11-04 16:55 UTC

**Comment by Mercury13** [comment] 2023-11-04 18:10
Strange. NOT A SINGLE character with this mark renders properly.

**Comment by Mercury13** [comment] 2023-11-04 18:15
(and even wrote a toolkit to write XMLs exactly in your style)

**Comment by Mercury13** [comment] 2023-11-04 21:13
Of course I made a fixup font, what to do, and triple baluda is fixed up too. But I’d never come with the latter, at least it’s visible somehow.

**Comment by lianghai** [comment] 2023-11-04 21:33
> NOT A SINGLE character with this mark renders properly.

You keep saying it’s not rendering “properly”. Then when you’re asked how it’s not rendering “properly”, you admit, well, it doesn’t have to render in the the way you want (within the default line box). And you don’t even have a use case from real texts. That’s the contradiction I’ve been trying to understand.

> No one told me which characters may carry this mark and which cannot.

If you’re asking for changes, you’re supposed to know that, because your suggestions should be based on the actual use cases. I’m not able to answer every single question from you, when I’m already busy dealing with your contradicting suggestions and trying to figure out what your suggestion is even based on.

The usage of MONGOLIAN LETTER ALI GALI DAGALGA is badly understood, and improving its font support naturally needs to start with clarifying how it’s used in texts. One of the common understandings is that it’s used to transcribe the [Tibetan vowel killer](https://en.wikipedia.org/wiki/Virama) on a consonant letter (with or without a following vowel _a_). But in any case, it’s used in the Hudum Ali Gali orthography, which is why @Kushim-Jiang (given the limited consensus about how it’s used in texts) simply made sure it doesn’t clash with Hudum Ali Gali glyphs:

> … so in order to avoid collision with all the glyphs used in Hudum Ali Gali, …

Right, it’s not beautiful. No one is forcing you to believe the situation is clear. But we’re asking you to make suggestions for actual texts.

Next time, when you want to suggest something, explain why the status quo is not acceptable for use cases in real texts—which you failed to do. If you keep ignoring our complaints about how you fail to establish a solid foundation for your suggestion, it’s gonna be a waste of time for both sides.

I’ve already wasted too much time here. This is my last comment in this thread.
